name: (title)<i>LOREBUSTER</i>
description: <div class="trailer-container"><iframe width="560" height="315" src="https://www.youtube.com/embed/zzliIB_IUGE?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
meta_description: "LOREBUSTER"

markdown: kramdown
#unsupported# highlighter: pygments
highlighter: rouge
logo: true
paginate: 15
baseurl: /lorebuster_www/
#domain_name: 'http://lorebuster.com'
#google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
#url:            'blog url'
#author:         'Your Name'
