name: LOREBUSTER
description:
meta_description: "LOREBUSTER"

markdown: kramdown
#unsupported# highlighter: pygments
highlighter: rouge
logo: true
paginate: 15
baseurl: /lorebuster_www/
domain_name: 'https://lorebuster.com'
#google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://lorebuster.com'
author:         'Nick Muse'

# Custom
profile_pic_url: https://nickmuse.com
